# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -buildvcs=false
    ldflags:
      - '-X main.GitSHA={{.FullCommit}} -X main.Branch={{.Tag}}'
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - cmd: cosign
    signature: '${artifact}.sig'
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--oidc-provider=github-actions'
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes
    artifacts: all
    output: true

dockers:
  - image_templates:
      - 'ghcr.io/kymppi/kuura:latest'
      - 'ghcr.io/kymppi/kuura:{{ .Tag }}' # 1.1.0
      - 'ghcr.io/kymppi/kuura:{{ .Major }}' # 1
      - 'ghcr.io/kymppi/kuura:{{ .Major }}.{{ .Minor }}' # 1.1
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/kymppi/kuura
      - --label=org.opencontainers.image.source=https://github.com/kymppi/kuura
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
