// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: m2m.sql

package db_gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createM2MRoleTemplate = `-- name: CreateM2MRoleTemplate :exec
INSERT INTO m2m_session_templates (id, roles)
VALUES ($1, $2)
`

type CreateM2MRoleTemplateParams struct {
	ID    string   `json:"id"`
	Roles []string `json:"roles"`
}

func (q *Queries) CreateM2MRoleTemplate(ctx context.Context, arg CreateM2MRoleTemplateParams) error {
	_, err := q.db.Exec(ctx, createM2MRoleTemplate, arg.ID, arg.Roles)
	return err
}

const createM2MSession = `-- name: CreateM2MSession :exec
INSERT INTO m2m_sessions (
    id,
    subject_id,
    refresh_token,
    roles,
    expires_at
)
SELECT 
    $1 AS id,
    $2 AS subject_id,
    $3 AS refresh_token, -- hashed
    t.roles AS roles,
    $4 AS expires_at
FROM m2m_session_templates t
WHERE t.id = $5
`

type CreateM2MSessionParams struct {
	ID           string             `json:"id"`
	SubjectID    string             `json:"subject_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ID_2         string             `json:"id_2"`
}

func (q *Queries) CreateM2MSession(ctx context.Context, arg CreateM2MSessionParams) error {
	_, err := q.db.Exec(ctx, createM2MSession,
		arg.ID,
		arg.SubjectID,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.ID_2,
	)
	return err
}

const getM2MRoleTemplates = `-- name: GetM2MRoleTemplates :many
SELECT id, roles FROM m2m_session_templates
`

func (q *Queries) GetM2MRoleTemplates(ctx context.Context) ([]M2mSessionTemplate, error) {
	rows, err := q.db.Query(ctx, getM2MRoleTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []M2mSessionTemplate{}
	for rows.Next() {
		var i M2mSessionTemplate
		if err := rows.Scan(&i.ID, &i.Roles); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
