// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: services.sql

package db_gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppService = `-- name: CreateAppService :exec
INSERT INTO services (id, jwt_audience, name)
VALUES ($1, $2, $3)
`

type CreateAppServiceParams struct {
	ID          pgtype.UUID `json:"id"`
	JwtAudience string      `json:"jwt_audience"`
	Name        string      `json:"name"`
}

func (q *Queries) CreateAppService(ctx context.Context, arg CreateAppServiceParams) error {
	_, err := q.db.Exec(ctx, createAppService, arg.ID, arg.JwtAudience, arg.Name)
	return err
}

const deleteAppService = `-- name: DeleteAppService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteAppService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppService, id)
	return err
}

const getAppService = `-- name: GetAppService :one
SELECT id, jwt_audience, created_at, modified_at, name, description FROM services
WHERE id = $1
`

func (q *Queries) GetAppService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getAppService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.JwtAudience,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getAppServices = `-- name: GetAppServices :many
SELECT id, jwt_audience, created_at, modified_at, name, description FROM services
`

func (q *Queries) GetAppServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, getAppServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.JwtAudience,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
