// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db_gen

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, salt, verifier)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Salt     string `json:"salt"`
	Verifier string `json:"verifier"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Salt,
		arg.Verifier,
	)
	return err
}
