name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5.1.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
